### ISSUE TITLE
Very Important Issue

### ISSUE THREAD

**Issue by JatinAgnish** [initializesahib/infin-stable#2]
So overall it was working fine until today where it gave me this error code

ERROR _ X21T5 534YFD D +++  HAS UNDIFEND RESTART REQUIRED PLEAE LIST ALL BOOT 
ERROROR SYSETEM CORRUPT 
While code error =
![image](https://user-images.githubusercontent.com/70415972/100164480-c9af8100-2e6c-11eb-8b0e-a962a6fd8433.png)

**Comment by JatinAgnish** [comment]
Also I have got this error also 
We're no strangers to love
You know the rules and so do I
A full commitment's what I'm thinking of
You wouldn't get this from any other guy


I just wanna tell you how I'm feeling
Gotta make you understand


Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you


We've known each other for so long
Your heart's been aching but you're too shy to say it
Inside we both know what's been going on
We know the game and we're gonna play it

[Pre-Chorus 2]
And if you ask me how I'm feeling
Don't tell me you're too blind to see


Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you


(Ooh, give you up)
(Ooh, give you up)
(Ooh) Never gonna give, never gonna give (Give you up)
(Ooh) Never gonna give, never gonna give (Give you up)


We've known each other for so long
Your heart's been aching but you're too shy to say it
Inside we both know what's been going on
We know the game and we're gonna play it

I just wanna tell you how I'm feeling
Gotta make you understand


Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you

**Comment by initializesahib** [comment]
what
